apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc-snapshot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-hostpath-sc
  resources:
    requests:
      storage: 1Gi
  